abi_dir = 'artifacts/abi'
bin_dir = 'artifacts/bin'
binds_dir = 'bindings'
contracts_dir = 'contracts'
log_level = ''
private_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
rpc_addr = 'http://0.0.0.0'
rpc_port = '8545'
