abi_dir = 'artifacts/abi'
bin_dir = 'artifacts/bin'
binds_dir = 'bindings'
contracts_dir = 'contracts'
erc20_example_address = '0x66064c28aFE46cd6BC12F8e86f13163C2C654a60'
log_level = ''
private_key = '454A24AE73F58F8AE82B610371E8230A9AB887C8D9E63EBCA097E9E4ACEB7075'
rpc_addr = 'http://0.0.0.0'
rpc_port = '8545'
