abi_dir = 'artifacts/abi'
bin_dir = 'artifacts/bin'
binds_dir = 'bindings'
contracts_dir = 'contracts'
erc20_example_address = '0xAD75c8C55794314a84bc3D1bF69c2e7CE19dab12'
log_level = ''
private_key = '784526329A092F80E13FAAB7E634B4AA294113BF898A2E9EDEFAC039D2DAF174'
rpc_addr = 'http://0.0.0.0'
rpc_port = '8545'
