# THIS IS EXAMPLE CONFIG BUT IT CAN BE USED AS IS

abi_dir = 'artifacts/abi'
bin_dir = 'artifacts/bin'
binds_dir = 'bindings'
contracts_dir = 'contracts'
erc20_example_address = '0xE752Fc3CcAA3FCB21263ebC2753a161035DD6b70'
log_level = ''
private_key = '41221710A88C7284D5F5BDE53311CDFA22B20F2724F3F4DA60FE3F567669DF56'
rpc_addr = 'http://0.0.0.0'
rpc_port = '8545'
