name: Lint
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Required: setup-go, for all versions v3.0.0+ of golangci-lint
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.0
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v3.2.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.46.2
          args: --timeout 5m
          github-token: ${{ secrets.github_token }}
        # Check only if there are differences in the source code
        if: "env.GIT_DIFF"